name: Py tools - verificações com o Flake8

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configuração de Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install flake8
        run: |
          pip install flake8
      - name: Install pytest
        run: |
          pip install pytest
<<<<<<< HEAD
          pip install pytest-mock
=======
          pip install pytest
>>>>>>> 04c691370936e3345270d76634d04ad467370299
          pip install requests
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Verificacoes com pytest
        run: |
          pytest tests/
