name: Py tools

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configuração de Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv sync --dev
      - name: Lint with flake8
        run: |
          pipenv run flake8 src spam tests
      - name: Test with pytest
        run: |
<<<<<<< HEAD
          pipenv run pytest . --cov=.
      - name: Posting Coverage
        run: |
          pipenv run codecov
=======
          pipenv run pytest py_tools --cov=py_tools
      - name: Posting Coverage
        run: |
          pipenv run codecov


>>>>>>> 29c90f10d479c8fecfd6440a23e30d160ef55f76
